general_settings:
  radio_behavior: simple
  context_lines_leading: 0
  context_lines_trailing: 0
  layout_plugins:
    split_fields:
      enabled: false
      weight: 4
    visual_inline:
      enabled: true
      weight: 5
    unified_fields:
      enabled: false
      weight: 6
  visual_default_view_mode: full
  visual_inline_theme: admin
