_core:
  default_config_hash: vXqCJHgFQcKRrLvKMdrDLhb5wwrNOgBm8slRLjbFJVY
header_mobile_breakpoint: '1200'
full_width_containers:
  cnt_secondary_header: cnt_secondary_header
  cnt_footer: cnt_footer
  cnt_header_nav: 0
  cnt_page_title: 0
  cnt_content_top: 0
  cnt_content: 0
  cnt_content_bottom: 0
full_width_content_types:
  announcement: 0
  banner: 0
  event: 0
  faqs: 0
  location: 0
  page: 0
  recurring_dates: 0
  recurring_ride: 0
  ride: 0
  webform: 0
block_design_regions:
  content_top: content_top
  content_bottom: content_bottom
  secondary_header: 0
  navigation: 0
  slider: 0
  header: 0
  highlighted: 0
  help: 0
  sidebar_first: 0
  sidebar_second: 0
  content: 0
  footer: 0
boxed_layout: 1
sticky_footer: 1
boxed_layout_boxbg: '#ffffff'
box_max_width: '1580'
layout_max_width: '1320'
gutter_horizontal: '30'
gutter_vertical: '30'
gutter_container: '60'
gutter_horizontal_mobile: '30'
gutter_vertical_mobile: '30'
gutter_container_mobile: '30'
body_line_height: '1.6'
body_font_size: '16'
nav_font_size: '16'
headings_line_height: '1.1'
scale_factor: '1.34'
h1_font_size: '44'
h2_font_size: '38'
h3_font_size: '29'
h4_font_size: '21'
blockquote_font_size: '21'
blockquote_line_height: '1.5'
headings_letter_spacing: '0'
headings_uppercase: 0
headings_bold: 1
body_mobile_font_size: '14'
nav_mobile_font_size: '14'
h1_mobile_font_size: '52'
h2_mobile_font_size: '38'
h3_mobile_font_size: '29'
h4_mobile_font_size: '24'
body_font_face: SF_Segoe_Roboto
body_font_face_selector: body
headings_font_face: lucida
headings_font_face_selector: 'h1,h2,h3,h4,h5,h6,label,.field--label,.page-title, .html .tp-caption'
nav_font_face: SF_Segoe_Roboto
nav_font_face_selector: 'nav,nav ul li,nav a'
sitename_font_face: SF_Segoe_Roboto
sitename_font_face_selector: '.site-name, .navbar-brand'
blockquote_font_face: SF_Segoe_Roboto
blockquote_font_face_selector: 'blockquote, blockquote p'
portfolio_details: top
portfolio_sidebar: '4'
portfolio_images: sidecaption
region_cards:
  secondary_header: ''
  navigation: ''
  navigation_collapsible: ''
  highlighted: ''
  page_title: ''
  help: ''
  content_top: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
blockquote_mobile_font_size: '18'
divider_thickness: '8'
divider_length: '0'
divider_position: '1'
divider_color: ''
divider_color_custom: '#eeeeee'
page_title_breadcrumbs: 0
page_title_home_hide: 1
page_title_align: left
page_title_height: '110'
page_title_animate: '0'
page_title_image_opacity: '1'
page_title_image_style: cover
page_title_image_mode: normal
page_title_image_position: center_center
background_image_style: cover
background_image_position: center_center
background_image_attachment: fixed
header_top_layout: '0'
header_style: normal
header_top_bg_opacity: '0.4'
header_top_height: '100'
header_top_fixed: 1
header_top_sticky: 1
header_top_sticky_show: always
header_top_height_sticky_offset: '60'
header_top_height_scroll: '50'
header_top_bg_opacity_scroll: '1'
navbar_background: ''
navbar_background_custom: ''
header_block_background: ''
header_block_background_custom: ''
header_block_text_color: ''
header_block_text_color_custom: ''
menu_background: ''
menu_background_custom: ''
menu_text_color: ''
menu_text_color_custom: ''
menu_hover_background: ''
menu_hover_background_custom: ''
menu_hover_text_color: ''
menu_hover_text_color_custom: ''
dropdown_background: ''
dropdown_background_custom: ''
dropdown_text_color: ''
dropdown_text_color_custom: ''
dropdown_hover_background: ''
dropdown_hover_background_custom: ''
dropdown_hover_text_color: ''
dropdown_hover_text_color_custom: ''
hamburger_menu: three-dash
hamburger_animation: cross
menu_type: uppercase
menu_hover: opacity
menu_border_position: bottom
menu_border_animate: drop
menu_border_position_offset: '0'
menu_border_position_offset_sticky: '0'
menu_border_size: '2'
menu_border_color: ''
menu_border_color_custom: ''
header_mobile_height: '60'
secondary_header_hide: hidden_none
custom_css_site: ''
custom_javascript_site: ''
block_preset: custom
block_card: ''
block_background: ''
block_background_custom: '#eeeeee'
block_padding: '0'
block_border_radius: '0'
block_border: '0'
block_border_color: ''
block_border_color_custom: '#eeeeee'
title_font_size: h3
title_align: left
title_card: ''
title_background: ''
title_background_custom: '#eeeeee'
title_padding: '0'
title_border: '0'
title_border_radius: '0'
title_border_color: ''
title_border_color_custom: '#eeeeee'
title_sticker: 0
block_divider: 0
block_divider_custom: 0
block_divider_color: ''
block_divider_color_custom: '#eeeeee'
block_divider_thickness: '4'
block_divider_length: '10'
block_divider_spacing: '20'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://header_0.svg'
  url: ''
  use_default: 0
page_title_image: null
background_image: null
web_icons_upload: null
hidden_regions:
  navigation: 0
  navigation_collapsible: 0
  secondary_header: 0
  page_title: 0
  highlighted: 0
  header: 0
  content_top: 0
  content: 0
  content_bottom: 0
  sidebar_first: 0
  sidebar_second: 0
  footer: 0
popover_placement: top
tooltip_placement: 'auto top'
modal_enabled: 0
cdn_provider: ''
favicon:
  use_default: 0
  path: 'public://NSC favicon_0.jpg'
  mimetype: image/jpeg
color_scheme: default
color_palette_base: '#284ed9'
color_palette_basetext: '#ffffff'
color_palette_link: '#284ed9'
color_palette_accent1: '#05e993'
color_palette_accent1text: '#333333'
color_palette_accent2: '#284fd8'
color_palette_accent2text: '#ffffff'
color_palette_text: '#555555'
color_palette_headings: '#333333'
color_palette_card: '#eeeeee'
color_palette_cardtext: '#444444'
color_palette_footer: '#21252a'
color_palette_footertext: '#747a85'
color_palette_secheader: '#284fd9'
color_palette_secheadertext: '#fffffe'
color_palette_header: '#ffffff'
color_palette_headertext: '#696969'
color_palette_headerside: '#20252a'
color_palette_headersidetext: '#737a85'
color_palette_pagetitle: '#284fdb'
color_palette_pagetitletext: '#fffeff'
color_palette_graylight: '#cccccc'
color_palette_graylighter: '#ededed'
color_palette_silver: '#f1f1f1'
color_palette_body: '#efefef'
logo_height: '59'
second_header_sticky: 0
dropdown_width: '160'
header_mobile_fixed: 0
background_image_path: ''
page_title_breadcrumbs_align: right
page_title_breadcrumbs_separator: /
title_type:
  uppercase: 0
  bold: 0
  italic: 0
page_title_image_path: ''
color_palette: 'a:25:{s:4:"base";s:7:"#284ed9";s:8:"basetext";s:7:"#ffffff";s:4:"link";s:7:"#284ed9";s:7:"accent1";s:7:"#05e993";s:11:"accent1text";s:7:"#333333";s:7:"accent2";s:7:"#284fd8";s:11:"accent2text";s:7:"#ffffff";s:4:"text";s:7:"#555555";s:8:"headings";s:7:"#333333";s:4:"card";s:7:"#eeeeee";s:8:"cardtext";s:7:"#444444";s:6:"footer";s:7:"#21252a";s:10:"footertext";s:7:"#747a85";s:9:"secheader";s:7:"#284fd9";s:13:"secheadertext";s:7:"#fffffe";s:6:"header";s:7:"#ffffff";s:10:"headertext";s:7:"#696969";s:10:"headerside";s:7:"#20252a";s:14:"headersidetext";s:7:"#737a85";s:9:"pagetitle";s:7:"#284fdb";s:13:"pagetitletext";s:7:"#fffeff";s:9:"graylight";s:7:"#cccccc";s:11:"graylighter";s:7:"#ededed";s:6:"silver";s:7:"#f1f1f1";s:4:"body";s:7:"#efefef";}'
